language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 'stable'
  - 'lts/*'

install:
  - npm install

before_script:
  - npm prune

script:
  - npm test

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run build
        - npm run semantic-release

branches:
  only:
    - master
